hang-django-project/hang/urls.py
from django.contrib import admin
from django.urls import include, path

# REST API Imports
# from django.contrib.auth.models import User
# from rest_framework import routers, serializers, viewsets
#
#
# # Serializers define the API representation.
# class UserSerializer(serializers.HyperlinkedModelSerializer):
#     class Meta:
#         model = User
#         # I think these are the fields that get exposed to the API in JSON.
#         fields = ['url', 'username', 'email', 'is_staff']
#
#
# # ViewSets define the view behavior.
# class UserViewSet(viewsets.ModelViewSet):
#     queryset = User.objects.all()
#     serializer_class = UserSerializer
#
#
# # Routers provide an easy way to determine the URL Conf automatically
# router = routers.DefaultRouter()
# router.register(r'users', UserViewSet)

urlpatterns = [
    path('', include('hangapp.urls')),
    path('', include('frontend.urls')),
    path('admin/', admin.site.urls),

    # REST API stuff
    path('api-auth/', include('rest_framework.urls')),
    # path('', include(router.urls))
]

hang-django-project/hangapp/urls.py
from django.urls import path, include

from . import views

from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'options', views.OptionViewSet)
router.register(r'decisionViewSet', views.DecisionViewSet)
router.register(r'hangoutViewSet', views.HangoutViewSet)

urlpatterns = [
    # path('', views.index, name='index'),

    path('api/', include(router.urls)),  # REST API URLs generated by the Router

    # *** REST API URLs made by me (Function-based) ***
    # TODO Refactor this whole URL scheme because it's a mess
    # Decisions
    # path('api/decision/<int:pk>/', views.decision_detail),
    path('api/decision-add/', views.add_decision),
    # Hangouts
    # path('api/hangout/<int:pk>/', views.get_hangout_detail),
    path('api/hangout/<int:pk>/decision/', views.get_decision_for_hangout),
    path('api/hangout/<int:hangout_pk>/is-ready/', views.are_homies_ready),
    # Options
    path('api/decision/<int:pk>/options/', views.get_options_for_decision),
    path('api/option-add/<int:decision_pk>/', views.add_option),
    path('api/option-vote/<int:pk>/', views.vote_on_option),
    path('api/results/<int:decision_pk>/', views.get_results),
    # Homies
    path('api/homie/ready-up/', views.ready_up_homie),
    path('api/join-hangout/', views.api_join_hangout),
    path('api/join-hangout/<int:hangout_id>', views.api_join_hangout),
    path('api/user-exit/', views.logout_view),
    #
    # path('start', views.user_entry, name='startUser'),
    # path('start/<int:session_id>', views.user_entry_with_session,
    #      name='startUserWithSession'),
    # path('join', views.new_user_new_session, name='newUserNewSession'),
    # path('join/<int:session_id>', views.new_user_join_session,
    #      name='newUserJoinSession'),
    # path('addDecision/<int:session_id>/<int:user_id>',
    #      views.add_decision, name='addDecision'),
    # path('suggest/<int:decision_id>/<int:user_id>', views.suggest, name='suggest'),
    # path('voteSession/<int:session_id>/<int:user_id>',
    #      views.vote_session, name='voteSession'),
    # path('vote/<int:option_id>/<int:user_id>', views.vote, name='vote'),
    # path('results/<int:decision_id>', views.results, name="results"),
]

hang-django-project/hangapp/models.py
from enum import Enum

from django.contrib.auth import authenticate, login
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from rest_framework.request import Request

from .custom_config import *


# Create your models here.

class Vote(Enum):
    NO = 0
    NEUTRAL = 1
    YES = 2


class VoteDetail:
    def __init__(self, vote: int, time_passed: float):
        self.vote = Vote(vote)  # Ensure the int is either 0, 1, or 2
        self.time_passed = time_passed


class Option(models.Model):
    """Represents an option to vote on for a particular decision."""

    _authorBiasFactor = 0.8

    optionText = models.CharField(max_length=400)
    score = models.FloatField(default=0.0)
    author = models.ForeignKey(
        "hangapp.Homie", on_delete=models.CASCADE, related_name="author")
    decision = models.ForeignKey("Decision", on_delete=models.CASCADE)
    usersVoted = models.ManyToManyField("hangapp.Homie")

    def __str__(self):
        return f"Option: {self.optionText} with score {self.score}"

    def vote(self, user, vote_detail: VoteDetail):
        """The given user votes on this choice. Yes if inFavor is True,
        no if it is False, or neutral if undefined."""
        if self.usersVoted.all().contains(user):
            raise Exception('User has already voted')

        if vote_detail.vote == Vote.YES:
            vote_weight = 1
        elif vote_detail.vote == Vote.NO:
            vote_weight = -1
        else:
            assert (vote_detail.vote == Vote.NEUTRAL)
            vote_weight = 0

        # TODO do something with the time_passed param
        if user == self.author:
            vote_weight *= Option._authorBiasFactor
        self.usersVoted.add(user)
        self.score += vote_weight
        self.save()

    def get_score(self):
        return self.score

    def voting_finished(self):
        users_in_session = self.decision.session.users.all()
        print(f"Session: {users_in_session}")
        print(f"This Option: {self.usersVoted.all()}")
        return set(users_in_session) == set(self.usersVoted.all())


class Decision(models.Model):
    """Represents a decision that a group of friends is making."""

    decisionText = models.CharField(max_length=400)
    session = models.ForeignKey("hangapp.HangoutSession", on_delete=models.CASCADE)

    def __str__(self):
        return f"Decision: {self.decisionText}"

    def add_option(self, option):
        self.options.append(option)
        option.setParentDecision(self)

    def get_winner(self):
        options = self.option_set.all()
        winner = options[0]
        for option in options:
            score = option.get_score()
            if score > winner.get_score():
                winner = option
        return winner

    def voting_finished(self) -> bool:
        for option in self.option_set.all():
            if not option.voting_finished():
                return False
        return True


class Homie(models.Model):
    """Represents a single user of the web app. Currently, only used
    to identify who made a particular decision or option."""

    username = models.CharField(max_length=100)
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    is_ready = models.BooleanField(default=False)

    def __str__(self):
        return self.username

    def ready_up(self):
        self.is_ready = True
        self.save()

    @staticmethod
    def get_homie_from_request(request: Request):
        # Get the user from the request body
        try:
            username = request.data['username']
            print(username)
        except KeyError:
            raise KeyError("No username included in request")
        # try to authenticate the user
        user: User = authenticate(request, username=username, password=DEFAULT_GLOBAL_PASSWORD)
        if user is not None:
            # Login as the user, which already exists in the database
            # *** This might not be necessary since we are still authenticating on every request. ***
            login(request, user)
        else:
            # User didn't exist already, so make a new one
            try:
                user = User.objects.create_user(username=username, password=DEFAULT_GLOBAL_PASSWORD)
            except ValueError:
                raise ValueError("get_homie(): request didn't provide a username")
            # *** This might not be necessary since we are still authenticating on every request. ***
            login(request, user)

        if hasattr(user, 'homie'):
            return user.homie
        else:
            return Homie.objects.create(pk=user.id, username=user.username)


class HangoutSession(models.Model):
    """Represents a session of decision-making by a group of friends."""

    creator = models.ForeignKey(
        Homie, on_delete=models.CASCADE, related_name="creator")
    users = models.ManyToManyField(Homie)

    def __str__(self):
        return f"Session created by {self.creator}"

    def join_homie(self, homie):
        self.users.add(homie)
        print(f"Just added homie {homie.username} to session {self.id}")
        print(self.users.all().values())

    def are_homies_ready(self):
        for homie in self.users.all():
            if not homie.is_ready:
                return False
        return True

    def get_invite_link(self):
        return reverse('startUserWithSession', args=(self.id,))

hang-django-project/hangapp/models/decision.py
from django.db import models

class Decision(models.Model):

    def __init__(self) -> None:
        self.prompt = ""

    def __init__(self, prompt) -> None:
        self.prompt = prompt
        self.options = []

    def __str__(self):
        return self.prompt

    def setParentSession(self, parent):
        self.parentSession = parent

    def getParentSession(self):
        return self.parentSession

    def addOption(self, option):
        self.options.append(option)
        option.setParentDecision(self)

    def getOptions(self):
        return self.options

    def getWinner(self):
        winner = self.options[0]
        for option in self.options:
            score = option.get_score()
            if score > winner.get_score():
                winner = option

        return winner

    def isFinished(self) -> bool:
        for option in self.options:
            if not option.votingComplete():
                return False
        
        return True

hang-django-project/hangapp/models/option.py
from django.db import models

class Option(models.Model):

    _authorBiasFactor = 0.8

    def __init__(self, name, author) -> None:
        self.name = name
        self.score = 0 
        self.votes = []
        self.score = 0
        self.author = author
    
    def __str__(self):
        return f"Option: {self.name} with score {self.score}"

    def setParentDecision(self, parent):
        self.parentDecision = parent

    def getParentDecision(self):
        return self.parentDecision

    def _vote(self, user, value):
        # check to see if this user has voted already and raise an error if so
        self.votes.append((user, value))
        self.score += value

    def voteYes(self, user):
        if user == self.author:
            self._vote(user, 1 * Option._authorBiasFactor)
        else:
            self._vote(user, 1)

    def voteNo(self, user):
        if user == self.author:
            self._vote(user, -1 * Option._authorBiasFactor)
        else:
            self._vote(user, -1)

    def voteNeutral(self, user):
        self._vote(user, 0)
    
    def getScore(self):
        sum = 0
        for vote in self.votes:
            sum += vote[1]
        assert sum == self.score
        return self.score

    def votingFinished(self):
        users = set(self.parentDecision.getParentSession().getUsers())
        # for user in users:
        usersVoted = set()
        for vote in self.votes:
            usersVoted.add(vote[0])
        

        print(users)
        print(usersVoted)
        return usersVoted == users

hang-django-project/hangapp/models/user.py
from django.db import models

class User(models.Model):
    
    username = models.CharField(max_length=100)

    def __init__(self) -> None:
        self.username = ""
        
    def __init__(self, username) -> None:
        self.username = username

    def __str__(self):
        return self.username

hang-django-project/hangapp/templates/hangapp/join.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'hangapp/style.css' %}">
    <title>Session started by {{session.creator.username}} | HangApp</title>
</head>

<body>
    <div class="mainDiv">
        <h1>Session started by {{session.creator.username}}</h1>
        <em>Contributing as {{user.username}} </em>

        <p>What are we deciding on?</p>
        {% for decision in session.decision_set.all %}
        <div class="decision">
            <li>{{decision.decisionText}}</li>
        </div>
        {% endfor %}

        <form action="{% url 'addDecision' session.id user.id %}" method="POST">
            {% csrf_token %}
            <input type="text" name="decisionText" id="newDecisionBox">
            <input type="submit" value="Add Decision">
        </form>
        
        {% if session.decision_set.first %}
        <form action="{% url 'voteSession' session.id user.id %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="Start Voting">
        </form>
        
        <div class="shareableLink">
            <p>Invite others! Right-click to copy and share with friends.</p>
            <a target="_blank" href="{{session.getInviteLink}}">Invite Link</a>
        </div>
        {% endif %}

    </div>
</body>

</html>

hang-django-project/hangapp/templates/hangapp/results.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'hangapp/style.css' %}">
    <title>Results | HangApp</title>

    <script>
        function show(){
            results = document.getElementById('detailedResults');
            results.style.display = "inline";
            butt = document.getElementById('button');
            butt.innerHTML = "Hide Detailed Results";
            butt.onclick = hide;
        }
        function hide(){
            results = document.getElementById('detailedResults');
            results.style.display = "none";
            butt = document.getElementById('button');
            butt.innerHTML = "Show Detailed Results";
            butt.onclick = show;        
        }
    </script>
</head>

<body>
    <div class="mainDiv">
        <h2>Results</h2>

        {% if decision.votingFinished %}
        Voting is finished!
        <h2>{{ decision.decisionText }}</h2>
        <h3>Winner:</h3>
        <div class="results">
            
            <h1>{{ decision.getWinner.optionText }}</h1>
            <button id="button" onclick="show()">Show Detailed Results</button>
            <div id="detailedResults" style="display:none">
                <table id="detailedResultsTable">
                    <tr>
                        <td><em>Option</em></td>
                        <td><em>Score</em></td>
                    </tr>
                    {% for option in decision.option_set.all %}
                    <tr>
                        <td>{{option.optionText}}</td>
                        <td>{{option.score}}</td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
            {% else %}
            Waiting on others to vote. Try refreshing in a few.
            {% endif %}
        </div>
    </div>
</body>

</html>

hang-django-project/hangapp/templates/hangapp/start.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'hangapp/style.css' %}">
    <title>Welcome | Hangapp</title>
</head>

<body>
    <div class="mainDiv">
        <h1>Welcome</h1>

        <p>Enter your name to get started.</p>
        {% if session %}
        <em>Joining {{session}}</em>
        <form action="{% url 'newUserJoinSession' session.id %}" method="post">
            {% csrf_token %}
            <input type="text" name="username" id="usernameInput">
            <input type="submit" value="Start a Session">
        </form>
        {% else %}
        <form action="{% url 'newUserNewSession' %}" method="post">
            {% csrf_token %}
            <input type="text" name="username" id="usernameInput">
            <input type="submit" value="Start a Session">
        </form>
        {% endif %}

    </div>
</body>

</html>

hang-django-project/hangapp/templates/hangapp/suggest.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'hangapp/style.css' %}">
    <title>Suggesting for {{decision.decisionText}} | HangApp</title>
</head>

<body>
    <div class="mainDiv">
        <div class="decision mainDiv">
            <h1>{{ decision.decisionText }}</h1>
            <em>Suggesting as {{user}}</em>
            <div class="option">
                <ul>
                    {% for option in decision.option_set.all %}
                    <li class="optionText">{{option.optionText}}</li><br>
                    {% endfor %}
                </ul>
            </div>

            <h3>Suggest: </h3>
            <form action="{% url 'suggest' decision.id user.id %}" method="POST">
                {% csrf_token %}
                <input type="text" name="optionText" id="addOptionTextBox">
                <input type="submit" value="Add Suggestion">
            </form>
            {% if decision.option_set.first %}
            <form action="{% url 'vote' decision.option_set.first.id user.id %}" method="POST">
                {% csrf_token %}
                <input type="submit" value="Start Voting">
            </form>
            {% endif %}
        </div>
    </div>
</body>

</html>

hang-django-project/hangapp/templates/hangapp/vote.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'hangapp/style.css' %}">
    <title>Vote on {{option.optionText}} | Hangapp</title>
</head>

<body>

    <script>
        {
            % comment %
        }

        function vote(voteCode, optionId) {
            switch (voteCode) {
                case "0":
                    write("voted no", `${optionId}out`);
                case "1":
                    write("voted neutral", `${optionId}out`);
                case "2":
                    write("voted yes", `${optionId}out`);
                default:
                    write("what", `${optionId}out`);
            }
        }

        function write(text, id) {
            document.getElementById(id).innerHTML = text;
        } {
            % endcomment %
        }
    </script>

    <div class="mainDiv">
        <h1>Vote on {{option.decision.decisionText}}</h1>
        <em>Voting as {{user.username}}</em>
        <div>
            <h3 class="option">{{option.optionText}}</h3>
            <form action="{% url 'vote' option.id user.id %}" method="POST">
                {% csrf_token %}
                <button name="vote" value="no" class="voteButton">❎</button>
                <button name="vote" value="neutral" class="voteButton">🤷‍♂️</button>
                <button name="vote" value="yes" class="voteButton">✅</button>
            </form>
        </div>
    </div>


</body>

</html>